README_cn.md

- Fix translation of `README_cn.md`

Fix README_cn.md translation

---

README.md
README_cn.md

update project url in readme

---

README.md
README_cn.md
docs/developer.md

Add Developer Guide

---

llmserve/backend/llm/pipelines/default_transformers_pipeline.py

Fix: https://github.com/OpenCSGs/llm-inference/issues/16

Fix default pipeline output problem

---

llmserve/backend/llm/predictor.py

`llm-inference` support start multiple `worker` for one deployment.
the design expect to handle batch prompts, do load balance among workers. then to short the inference duration for a batch

Enable multiple workers cooperated on batch prompt

---

README.md
README_cn.md
docs/git_server_s3_storage.md

Update document for download model from OpenCSG model hub

Update document for download model from OpenCSG model hub

---

build_llmserve_image.sh
build_llmserve_image_base.sh
deploy/kuberay/starray.yaml
deploy/ray/Dockerfile
docs/deploy_on_kubernetes.md

Push image to opencsg registry for deploy on K8s

Push image to opencsg registry

---

llmserve/backend/llm/initializers/hf_transformers/base.py
llmserve/backend/llm/pipelines/_base.py
llmserve/backend/llm/pipelines/default_pipeline.py
llmserve/backend/llm/predictor.py
llmserve/backend/server/models.py
models/text-generation--Qwen--Qwen-7B.yaml

Qwen is very specific, it require extra lib beside basic `transformer` .etc. so i have to adopt `run_env` to let ray install these libs runtime.
if internet limited, I guess we have to proposal user install these libs in advance in ray cluster node image building phase

Refine some parameters for initialization(will keep refining...) and fix Qwen issues

---

llmserve/backend/llm/pipelines/_base.py
llmserve/backend/llm/pipelines/default_transformers_pipeline.py

devicemap not work on mps, since put data in wrong device, fix it

---

models/text-generation--opencsg--opencsg-deepseek-coder-1.3b-v0.1.yaml

Refine the config as the model card in huggingface: https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-instruct

refine config for model: deepseek-coder-1.3b

---

models/summarization--facebook--bart-large-cnn.yaml
models/text-classification--distilbert-base-uncased-finetuned-sst-2-english.yaml
models/text-generation--facebook--opt-125m-pipeline.yaml
models/text-generation--opencsg--opencsg-CodeLlama-7b-v0.1-pipeline.yaml
models/text-generation--opencsg--opencsg-starcoder-15B-v0.1-pipeline.yaml

fix broken yamls

---

models/text-generation--Qwen--Qwen1.5-72B-Chat.yaml

add parameter for timeout

---

llmserve/backend/llm/initializers/hf_transformers/deepspeed.py
llmserve/backend/llm/pipelines/_base.py
llmserve/backend/llm/pipelines/default_pipeline.py
llmserve/backend/llm/predictor.py
llmserve/backend/server/models.py
models/text-generation--bigscience--bloom-3b.yaml
setup.py

integrated `deepspeed inference`, still some issue need figure out, just submit basic code base to avoid missing something

enable deepspeed inference

---

llmserve/backend/llm/initializers/hf_transformers/deepspeed.py
llmserve/backend/llm/pipelines/default_transformers_pipeline.py

The two parameters both are very useful to accelerate inference speed.

enable "use_bettertransformer" and "torch_compile"

---

llmserve/backend/llm/pipelines/default_pipeline.py
llmserve/backend/llm/pipelines/default_transformers_pipeline.py
llmserve/backend/llm/pipelines/utils.py
llmserve/backend/llm/predictor.py
llmserve/backend/llm/utils.py
llmserve/backend/server/utils.py
models/text-generation--facebook--blenderbot-400M-distill.yaml
setup.py

see https://huggingface.co/docs/transformers/main/en/chat_templating,
I think it's useful especially for instruct/chat model

Enable chat template for huggingface transformer

---

README.md
deploy/ray/Dockerfile-base
llmserve/backend/server/app.py
models/text-generation--Qwen--Qwen1.5-72B-Chat.yaml
models/text-generation--gpt2.yaml

Test the following command:
```
llmserve start experimental --model=./model/text-generate--gpt2.yaml
llmserve start serving --model=./model/text-generate--gpt2.yaml
llmserve start apiserver
curl -H "Content-Type: application/json" -H "user-name: default"  -d '[{"model_id": "gpt2", "model_task": "text-generation", "model_revision": "main", "is_oob": true, "scaling_config": {"num_workers": 1, "num_gpus_per_worker": 0,"num_cpus_per_worker": 3}}]' -X POST "http://127.0.0.1:8000/api/start_serving"
curl -H "Content-Type: application/json" -X POST -d '[{"prompt":"How can you"}, {"prompt": "What can I do"}]' "http://127.0.0.1:8000/default-8ec71bfe69a5/gpt2/run/predict"
curl -H "Content-Type: application/json" -X POST -d '[{"prompt":"How can you"}]' …
```

Update ray to 2.9.3

---

llmserve/backend/llm/pipelines/default_pipeline.py
llmserve/backend/llm/pipelines/default_transformers_pipeline.py

Same problem as #62  mentioned, but for pipeline defined as "defaulttransformers"

Fix json format issue for "transformerpipeline"

---

llmserve/backend/llm/engines/vllm/vllm.py

For chat/instruct model, must apply the chat template or the model output is suck

Enable chat template applied for vllm integration

---

llmserve/backend/server/run.py
models/text-generation--facebook--opt-125m.yaml

The scale out policy in deployments is not consistent, it will caused scale out behavior weird.

Make scale out policy consistent between deployments

---

setup.py

for now, we only support vllm>=0.2.0,<0.2.6,
will research and implements on new version soon

correct vllm version

---

llmserve/backend/llm/engines/generic.py
llmserve/backend/llm/pipelines/llamacpp/llamacpp_pipeline.py
models/text-generation--Qwen1.5-72B-Chat-GGUF.yaml
models/text-generation--Qwen1.5-7B-Chat-GGUF.yaml

enhance llamacpp integration to share soma logic between streaming and predict

---

llmserve/backend/llm/engines/generic.py
llmserve/backend/llm/predictor.py

in this scenario, should return correct value event it's not stream
should not crash

fix issue: non-support streaming pipeline cannot work when call it as stream

---

llmserve/backend/server/run.py

fix issue: vllm cannot address runtime_env

---

docs/deploy_on_kubernetes.md
docs/developer.md
docs/quick_start.md
llmserve/api/cli.py

from `llm-serve start serving` -> `llm-serve start serving-rest`
from `llm-serve start experimental` -> `llm-serve start serving-ui`

refine cli, make cli self-explanatory

---

llmserve/api/sdk.py

the `llm-serve list serving` is broken, get nothing like this:
```
{
"default": {
"status": {
"default": {
"application_status": "RUNNING",
"deployments_status": {}
}
},
"url": {}
}
}
```

fix llm-serve list

---

docs/quick_start.md

fix: https://github.com/OpenCSGs/llm-inference/issues/100

update quickstart.md to remove evaluate

---

llmserve/backend/llm/engines/_base.py
llmserve/backend/llm/engines/generic.py
llmserve/backend/llm/engines/vllm/vllm.py
llmserve/backend/llm/pipelines/_base.py
llmserve/backend/llm/pipelines/default_pipeline.py
llmserve/backend/llm/pipelines/default_transformers_pipeline.py
llmserve/backend/llm/pipelines/llamacpp/llamacpp_pipeline.py
llmserve/backend/llm/predictor.py
llmserve/backend/llm/utils.py
llmserve/backend/server/app.py
llmserve/backend/server/models.py
llmserve/common/backend.py

This pr not include vllm, since its  implements is different from others[transformer auto class, transformer pipeline, deepspeed and llamacpp]

suport on-fly generate params

---

docs/quick_start.md
llmserve/backend/server/app.py
llmserve/backend/server/models.py

Add new api in openai style

---

models/text-generation--opencsg--csg-wukong-1B.yaml

Add csg wukong model

---

llmserve/backend/server/app.py

Serve run in thread

---

llmserve/backend/server/app.py

maybe caused by ray upgrade or pydantic  upgrade

fix ui concurrency setting
